baseURL = "https://snowcamp.io/"
languageCode = "fr"
title = "Snowcamp 2019"
googleAnalytics = ""

DefaultContentLanguage = "fr"
defaultContentLanguageInSubdir=true

[Languages]

[Languages.fr]
weight = 1
[Languages.en]
weight = 2
